# Studing fdasrvf | Julia

* Julia:
    * pkg: https://github.com/jdtuck/ElasticFDA.jl
    * documentation https://elasticfdajl.readthedocs.io/en/latest/


* All pkgs: http://research.tetonedge.net/software.html

## Loading data

In [2]:
using(ElasticFDA)
using CSV
using DataFrames

df = CSV.read("data_temp.csv", DataFrame)

100×17 DataFrame
 Row │ Column1  0            1            2            3            4          ⋯
     │ Int64    Float64      Float64      Float64      Float64      Float64    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  1.83285e-45  9.19395e-27  2.69583e-38  1.16925e-46  1.5979e-33 ⋯
   2 │       1  2.89475e-43  4.30648e-25  2.77371e-36  1.97666e-44  1.20762e-3
   3 │       2  4.02443e-41  1.77564e-23  2.51212e-34  2.94149e-42  8.03386e-3
   4 │       3  4.92503e-39  6.44461e-22  2.00277e-32  3.85314e-40  4.70466e-2
   5 │       4  5.30548e-37  2.05897e-20  1.4055e-30   4.44296e-38  2.42518e-2 ⋯
   6 │       5  5.03097e-35  5.79047e-19  8.68249e-29  4.50963e-36  1.10045e-2
   7 │       6  4.19942e-33  1.43347e-17  4.72136e-27  4.02922e-34  4.39548e-2
   8 │       7  3.08559e-31  3.12374e-16  2.25996e-25  3.16892e-32  1.54545e-2
   9 │       8  1.99571e-29  5.99201e-15  9.5224e-24   2.19388e-30  4.78314e-2 ⋯
  10 │       9  1.13623e-27  1.01177e-13  3.53185e-22  1.33698e-28  1.30312e-1
  11 │      10  5.69442e-26  1.50383e-12  1.15311e-20  7.17214e-27  3.1251e-17
  ⋮  │    ⋮          ⋮            ⋮            ⋮            ⋮            ⋮     ⋱
  91 │      90  1.755e-20    1.28228e-23  4.23222e-33  1.79181e-21  3.5198e-18
  92 │      91  5.4604e-22   3.07488e-25  5.07142e-35  5.12376e-23  1.3438e-19 ⋯
  93 │      92  1.49549e-23  6.49056e-27  5.34936e-37  1.28972e-24  4.51606e-2
  94 │      93  3.60538e-25  1.206e-28    4.96689e-39  2.8577e-26   1.33597e-2
  95 │      94  7.65123e-27  1.97253e-30  4.05956e-41  5.57373e-28  3.47892e-2
  96 │      95  1.4293e-28   2.83996e-32  2.92068e-43  9.56946e-30  7.97449e-2 ⋯
  97 │      96  2.3503e-30   3.59924e-34  1.84969e-45  1.44624e-31  1.60906e-2
  98 │      97  3.40202e-32  4.01532e-36  1.03116e-47  1.92399e-33  2.85794e-2
  99 │      98  4.33471e-34  3.94313e-38  5.06016e-50  2.25308e-35  4.46833e-3
 100 │      99  4.86178e-36  3.40857e-40  2.18581e-52  2.32253e-37  6.14961e-3 ⋯
                                                  12 columns and 79 rows omitted

In [3]:
names(df)

17-element Vector{String}:
 "Column1"
 "0"
 "1"
 "2"
 "3"
 "4"
 "5"
 "6"
 "7"
 "8"
 "9"
 "10"
 "11"
 "12"
 "13"
 "14"
 "time"

First column should be read as the index... Anyways, let's consider only the columns 2:17. So: 
* the shape of ```df[!,2:17]``` is 100x16. 
* the last columns is time: ```df[!,"time"]``` (alternative is ```df[!,17]```). 
* the leading 15 columns are the data: ```df[!,2:16]

In [4]:
size(df[!,2:17])

(100, 16)

In [5]:
df[1:2,:2:5]

2×4 DataFrame
 Row │ 0            1            2            3           
     │ Float64      Float64      Float64      Float64     
─────┼────────────────────────────────────────────────────
   1 │ 1.83285e-45  9.19395e-27  2.69583e-38  1.16925e-46
   2 │ 2.89475e-43  4.30648e-25  2.77371e-36  1.97666e-44

In [6]:
df[1:2,:15:17]

2×3 DataFrame
 Row │ 13           14           time      
     │ Float64      Float64      Float64   
─────┼─────────────────────────────────────
   1 │ 6.71373e-30  9.32424e-29  -1.0
   2 │ 3.95341e-28  5.05899e-27  -0.949495

In [7]:
df[1:2,"time"]

2-element Vector{Float64}:
 -1.0
 -0.9494949494949495

### srsf_align
* :param f: array of shape (M,N) of N functions with M samples
*  :param timet: vector of size M describing the sample points


Returns fdawarp type containing
*   :return fn: aligned functions - array of shape (M,N) of N functions with M samples
*   :return qn: aligned srsfs - similar structure to fn
*   :return q0: original srsfs - similar structure to fn
*   :return fmean: function mean or median - vector of length N
*   :return mqn: srvf mean or median - vector of length N
*   :return gam: warping functions - similar structure to fn
*   :return orig_var: Original Variance of Functions
*   :return amp_var: Amplitude Variance
*   :return phase_var: Phase Variance

In [8]:
@time res = srsf_align(Array(df[!, 2:16]), df[!, "time"], smooth=false, MaxItr=3);

Initializing...
Compute Karcher Mean of 15 functions in SRSF space..
updating step: r=1
updating step: r=2
updating step: r=3
maximal number of iterations reached
 12.544128 seconds (18.21 M allocations: 1.048 GiB, 3.71% gc time, 48.95% compilation time)


In [9]:
@time res = srsf_align(Array(df[!, 2:16]), df[!, "time"], smooth=false, MaxItr=3);

Initializing...
Compute Karcher Mean of 15 functions in SRSF space..
updating step: r=1
updating step: r=2
updating step: r=3
maximal number of iterations reached
  6.399286 seconds (22.41 k allocations: 14.607 MiB)


In [71]:
res.fn

100×4 Matrix{Float64}:
 1.83285e-45  9.19395e-27  2.69583e-38  1.16925e-46
 4.02443e-41  1.43347e-17  2.08702e-36  9.94177e-45
 5.30548e-37  2.20559e-15  1.26993e-34  1.97666e-44
 1.91977e-35  6.94485e-14  5.19533e-33  6.66702e-41
 3.78649e-35  1.50383e-12  2.00277e-32  1.50667e-38
 5.68948e-34  3.32102e-12  5.39581e-31  2.27703e-36
 2.12486e-33  5.1382e-12   1.05913e-30  2.70118e-34
 3.68078e-33  6.95539e-12  1.20829e-29  2.64748e-32
 8.02892e-32  8.77257e-12  4.41152e-29  2.19388e-30
 1.94424e-31  1.05898e-11  7.61475e-29  4.9869e-15
 3.08559e-31  1.24069e-11  1.24546e-27  2.49625e-14
 1.27182e-15  1.42241e-11  2.98341e-27  4.49381e-14
 1.75508e-14  1.60413e-11  4.72136e-27  6.49136e-14
 ⋮                                      
 6.49661e-14  5.78243e-14  1.0353e-15   8.60024e-15
 5.23117e-15  4.63181e-15  3.84553e-17  3.36577e-15
 2.1934e-16   1.9316e-16   1.12979e-18  6.05958e-16
 7.61799e-18  6.67239e-18  2.28728e-20  3.20804e-16
 2.0914e-19   1.82179e-19  9.81818e-23  3.56505e-17
 

In [70]:
res.

100-element Vector{Float64}:
 -1.0
 -0.9494949494949495
 -0.898989898989899
 -0.8484848484848485
 -0.797979797979798
 -0.7474747474747474
 -0.696969696969697
 -0.6464646464646464
 -0.595959595959596
 -0.5454545454545454
 -0.4949494949494949
 -0.4444444444444444
 -0.3939393939393939
  ⋮
  3.4444444444444446
  3.494949494949495
  3.545454545454545
  3.595959595959596
  3.646464646464646
  3.6969696969696972
  3.7474747474747474
  3.7979797979797976
  3.8484848484848486
  3.898989898989899
  3.94949494949495
  4.0

## documentation and github examples

In [64]:
timet = LinRange(0,1,101);
M = length(timet);
N = 5;
lam = 0.001;
center = [.3; .35];
center2 = [4; 4];
sd1 = .1;
gam_sd = 1;
num_comp = 5;
f_orig = zeros(M,N*length(center));
omega = 2*pi;
cnt = 1;
for ii = 1:length(center)
    global cnt
    tmp = Normal(center[ii], .1);
    tmp2 = Normal(center2[ii], sd1);
    for jj = 1:N
        f_orig[:, cnt] = rand(tmp2) * pdf.(tmp, timet);
        cnt+= 1;
    end
end

q_orig = f_to_srsf(f_orig,collect(timet));
y_orig = ones(size(q_orig,2));
y_orig[N+1:end] .= -1;

f = zeros(M, size(f_orig,2));
q = zeros(M, size(f_orig,2));
gam_orig = rgam(M, gam_sd, 2*N);
cnt = 1;
for ii = 1:length(center)
    global cnt
    for jj = 1:N
        f[:,cnt] = warp_f_gamma(collect(timet), f_orig[:,cnt], gam_orig[:,jj]);
        q[:,cnt] = f_to_srsf(f[:,cnt], collect(timet));
        cnt += 1;
    end
end

LoadError: UndefVarError: Normal not defined

In [63]:
# https://github.com/jdtuck/ElasticFDA.jl/blob/master/scripts/test.jl

using JLD2, Distributions, ProgressMeter, Interpolations, Plots
@load "test/simu_data.jld2"
include("src/types.jl")
include("src/misc_funcs.jl")
include("src/srsf_funcs.jl")
include("src/geometry.jl")
include("src/pair_warping_expomap.jl")
f1 = f[:,1]
f2 = f[:,9]
iter=20000
burnin=min(5000,iter/2)
alpha0=0.1
beta0=0.1
pbetas=[0.5,0.05,0.005,0.0001]
probs=[0.1,0.1,0.7,0.1]
propvar=1.0
init_coef=zeros(20)
npoints=200
extrainfo=false

using JLD2, ElasticFDA, Plots
@load "test/simu_data.jld2"
f1 = f[:,1]
f2 = f[:,21]
out = pair_warping_expomap(f1,f2,timet,propvar=1,extrainfo=true)

LoadError: ArgumentError: Package JLD2 not found in current path:
- Run `import Pkg; Pkg.add("JLD2")` to install the JLD2 package.


## Old

In [50]:
# this class provides alignment methods for functional data using the SRVF framework

obj = ElasticFDA.fdawarp(Array(df[!, 2:5]), df[!, "time"])

LoadError: MethodError: no method matching ElasticFDA.fdawarp(::Matrix{Float64}, ::Vector{Float64})
Closest candidates are:
  ElasticFDA.fdawarp(::Array{Float64, N} where N, ::Vector{Float64}, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Vector{Float64}, ::Vector{Float64}, ::Array{Float64, N} where N, ::Float64, ::Float64, ::Float64, ::Vector{Float64}, ::Float64, ::String, ::String, ::Vector{Float64}, ::Bool, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2
  ElasticFDA.fdawarp(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2

In [53]:
# this class provides alignment methods for functional data using the SRVF framework

obj = ElasticFDA.fdawarp(transpose(Array(df[!, 2:5])), df[!, "time"])

LoadError: MethodError: no method matching ElasticFDA.fdawarp(::LinearAlgebra.Transpose{Float64, Matrix{Float64}}, ::Vector{Float64})
Closest candidates are:
  ElasticFDA.fdawarp(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2
  ElasticFDA.fdawarp(::Array{Float64, N} where N, ::Vector{Float64}, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Vector{Float64}, ::Vector{Float64}, ::Array{Float64, N} where N, ::Float64, ::Float64, ::Float64, ::Vector{Float64}, ::Float64, ::String, ::String, ::Vector{Float64}, ::Bool, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2

In [43]:
# this class provides alignment methods for functional data using the SRVF framework

obj = ElasticFDA.fdawarp(Array(df[!, 2:5]), df[!, "time"])

LoadError: MethodError: no method matching ElasticFDA.fdawarp(::Matrix{Float64}, ::Vector{Float64})
Closest candidates are:
  ElasticFDA.fdawarp(::Array{Float64, N} where N, ::Vector{Float64}, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Vector{Float64}, ::Vector{Float64}, ::Array{Float64, N} where N, ::Float64, ::Float64, ::Float64, ::Vector{Float64}, ::Float64, ::String, ::String, ::Vector{Float64}, ::Bool, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N, ::Array{Float64, N} where N) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2
  ElasticFDA.fdawarp(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /home/leo/.julia/packages/ElasticFDA/d5Ypy/src/types.jl:2